name: Teste de Caminho

on:
  push:
    branches: ["principal", "main"]

permissions:
  contents: read

jobs:
  diagnostico:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Listar Diretorios
        run: ls -la
